### ISSUE TITLE
Support for latest versions of Django (4+), Graphene (3+), Graphene Django (3+) ?

### ISSUE THREAD

**Issue by thomas-arun** [devind-team/graphene-django-filter#71]
I am working on a project where I have the latest versions of all of the above packages. As soon as I installed `graphene-django-filter`, pip started uninstalling and downgrading my packages since `graphene-django-filter` has a hard upper limit on its dependencies.

I just wanted to know if there is any particular reason for this and if there are any compatibility issues already noted because of which this has been kept?

If not, can we bump up the dependency versions?

**Comment by rapsealk** [comment]
I think this repository has not been maintained for more than an year. I forked one and updated the pacakge dependencies.

**Comment by thomas-arun** [comment]
Maybe if the maintainers want some support, I am happy to help.

**Comment by Luferov** [comment]
Hi guys!
Now our team is a little dispersed and there is no strength to support. However, if you really need the functionality of this library, we can implement it.

@thomas-arun I sent an invitation for you to take part in this project

**Comment by thomas-arun** [comment]
Thank you @Luferov, I shall put in few PRs with potential fixes.

**Comment by Luferov** [comment]
> Thank you @Luferov, I shall put in few PRs with potential fixes.

Thank you so mush for you job!

**Comment by thomas-arun** [comment]
#73 
@Luferov I have put in a pull request for bumping the package versions. Can you take a look and merge?
Do you need me to create a release too?

**Comment by thomas-arun** [comment]
@Luferov Thank you for approving the PR, there were few other fixes I needed to do for the GitHub actions. They are all fixed now and the CI action has completed successfully. 

Will you be able to create a new release to PyPi? I am not sure what steps are followed to do that.
Thanks in advance

**Comment by thomas-arun** [comment]
I fixed the commit message part. Didn't know `python semantic releaser` was being used. 
I've successfully released v0.6.5 

Closing this ticket
